#!/bin/bash

x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"

clear
cat /etc/payloads
echo "$f Qual Host Deseja Adicionar? $x"
read hostt
 
echo "$hostt" >> /etc/payloads
squid -k reconfigure > /dev/null 2> /dev/null
squid3 -k reconfigure > /dev/null 2> /dev/null
echo
echo "$f Host $a $hostt $f Adicionada Com Sucesso!!! $x"
