#!/bin/bash

x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"

clear
 
echo -e "$f Qual O Nome Do Usuario Que Voce Quer Mudar A Data De Validade $x :"
read namers
 if cat /etc/passwd |grep $namers: > /dev/null
   then 
   echo " "
   else
   clear
   echo -e "$a Usuario $namers Nao Existe $x"
   sleep 4
   Crazzy
 fi
   clear
   echo -e "$f Qual A Nova Data No Formato AAAA/MM/DD $x"
   read date
   date chage -E $date $namer 2> /dev/null
   echo -e "\033[1;36mUsuario $namers Data: $date\033[0m"
