#!/bin/bash

x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"
clear
   echo -e "$f                 Monitoramento Crazzy                  $x"
   echo -e "$f         Usuario                     Conectados                $x"
   echo -e " $a      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ $x"
   for usuario in `awk -F : '$3 >= 1000 { print $1 }' /etc/passwd |grep -v "nobody"`; do
   conectados=$(ps x |grep -vi '[a-z]$usuario' |grep -vi '$usuario[a-z]' |grep -v '[1-9]$usuario' |grep -v '$usuario[1-9]' |grep $usuario |grep $usuario |grep 'sshd:' |grep [priv] |wc -l)     
   tput setaf 6 ; tput bold ; printf      '          %-32s%s\n' $usuario $conectados; tput sgr0     
   echo -e " $a      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ $x"
   done
