#!/bin/bash
 
 clear
 
x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"
 
detalhes  () {
clear
 
script="$a CrazzyScript $x"
dono="$a MatheusR $x"
versao="$a V1.0 $x"
data="$a 10/04/2017 $x"
 
echo -e "$f Nome Do Script: $script"
echo -e "$f Versão: $versao"
echo -e "$f Desenvolvido Por: $dono"
echo -e "$f Data De Criação: $data"
} 
 
echo -e "\033[0;31m------------------------------------------------- $x"
echo -e "\033[1;36mBem Vindo Ao Menu De Opções Do CrazzyScript,
Toda Vez Que Quizer Entra No Menu, Digite \033[2;31mCrazzy \033[0m"
echo
echo -e "\033[1;31m
[$f 0$a ] $f  Sair Do Menu $a
[$f 1$a ] \033[1;36m  Configurar Sua Vps \033[1;31m
[$f 2$a ] \033[1;36m  Criar Usuarios \033[1;31m
[$f 3$a ] \033[1;36m  Deletar Usuarios \033[1;31m
[$f 4$a ] \033[1;36m  Mudar Senha De Usuario \033[1;31m
[$f 5$a ] \033[1;36m  Mudar Data De Validade \033[1;31m
[$f 6$a ] \033[1;36m  Monitorar Usuarios \033[1;31m
[$f 7$a ] \033[1;36m  Banner $a
[$f 8$a ] $f  Adicionar Host $a
[$f 9$a ] $f  Detalhes Do Script $a
[$f 10$a ] $f Desinstalar o CrazzyScript $x"        
echo -e "\033[0;31m------------------------------------------------- $x"
echo   
echo -e "$a Escolha Uma Opção"
read -p ":" menu
  
echo
case $menu in
 
0)
exit; ;;
1)
echo 'Port 443    
PermitRootLogin yes 
PubkeyAuthentication yes
PasswordAuthentication yes' >> /etc/ssh/sshd_config
 
echo "minhaclaro.claro.com.br 
recargafacil.claro.com.br 
frontend.claro.com.br 
appfb.claro.com.sv 
empresas.claro.com.br 
d1n212ccp6ldpw.cloudfront.net 
claro-gestoronline.claro.com.br 
forms.claro.com.br 
golpf.claro.com.br 
logtiscap.claro.com.br 
www.recargafacil.claro.com.br 
.vivo.com.br 
.bradescocelular.com.br 
.claroseguridad.com" > /etc/payloads
 
ubuntu16 () {
    clear
   echo -e "\033[0;36m======================================\033[0m"
   echo -e "\033[0;32mCONFIGURANDO SEU SQUID...\033[0m"
   sleep 3
   echo -e "\033[0;33m      Sucesso...\033[0m"
   sleep 1 
   echo -e "\033[0;32mCONFIGURANDO SUA VPS...\033[0m"
   sleep 3
   echo -e "\033[0;33m      Sucesso...\033[0m"
   echo -e "\033[0;36m======================================\033[0m"
   sleep 2
     
    apt-get update&
    apt-get install -y squid curl nano sysv-rc-conf ulatency ulatencyd&
     
    cd /etc/ssh/
 
    echo "$(sed 's/22/443/g' sshd_config)" > sshd_config
    echo "" >> sshd_config    
    echo "Port 22" >> sshd_config 
     
    ip=$(wget -qO - icanhazip.com)
     
    echo "# PORTAS DE ACESSO NO SQUID" > /etc/squid/squid.conf
    echo "http_port 80" >> /etc/squid/squid.conf
    echo "http_port 8080" >> /etc/squid/squid.conf
    echo "http_port 8799" >> /etc/squid/squid.conf
    echo "http_port 3128" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "# NOME DO SERVIDOR" >> /etc/squid/squid.conf
    echo "visible_hostname Crazzy" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "# ACL DE CONEXAO" >> /etc/squid/squid.conf
    echo "acl accept src $ip" >> /etc/squid/squid.conf
    echo "acl ip url_regex -i $ip" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "# CACHE DO SQUID" >> /etc/squid/squid.conf
    echo "cache_mem 200 MB" >> /etc/squid/squid.conf
    echo "maximum_object_size_in_memory 32 KB" >> /etc/squid/squid.conf
    echo "maximum_object_size 1024 MB" >> /etc/squid/squid.conf
    echo "minimum_object_size 0 KB" >> /etc/squid/squid.conf
    echo "cache_swap_low 90" >> /etc/squid/squid.conf
    echo "cache_swap_high 95" >> /etc/squid/squid.conf
    echo "cache_dir ufs /var/spool/squid 100 16 256" >> /etc/squid/squid.conf
    echo "access_log /var/log/squid/access.log squid" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "" >> /etc/squid/squid.conf
    echo "# ACESSOS ACL" >> /etc/squid/squid.conf
    echo "http_access allow accept" >> /etc/squid/squid.conf
    echo "http_access allow ip" >> /etc/squid/squid.conf
    echo "http_access deny all" >> /etc/squid/squid.conf
    echo "cache deny all" >> /etc/squid/squid.conf
 
    sysv-rc-conf squid on
 
    service squid restart
 
    service ssh restart
     
    clear
   echo -e "\033[0;36m====================================================\033[0m"
   echo -e "\033[0;31mDesenvolvedor Do Script:\033[0;36m@MatheusR\033[0m"
   echo -e "\033[0;31mSeu Sistema Operacional: $f Ubuntu 16\033[0m"
   echo -e \033[0;31mIp Da Sua VPS:\033[0;36m $ip\033[0m"
   echo -e "\033[0;31mSeu Squid Esta Configurado Para Operar Nas Portas:\033[0;36m80, 8080, 3128, 8799\033[0m"
   echo -e "\033[0;31mDropbear Nas Portas:\033[0;36m22 e 443\033[0m"
   echo -e "\033[0;31mVoce Tambem Pode Usa O Ip\033[0;33m127.0.0.1\033[0;31mComo Ip SSH\033[0m"
   echo -e "\033[0;36m=====================================================\033[0m"
   sleep 6
   Crazzy
 
 
}
 
 
ubuntu () {
 
clear
echo -e "\033[0;36m======================================\033[0m"
   echo -e "\033[0;32mCONFIGURANDO SEU SQUID...\033[0m"
   sleep 3
   echo -e "\033[0;33m      Sucesso...\033[0m"
   sleep 1 
   echo -e "\033[0;32mCONFIGURANDO SUA VPS...\033[0m"
   sleep 3
   echo -e "\033[0;33m      Sucesso...\033[0m"
   echo -e "\033[0;36m======================================\033[0m"
   sleep 2
     
    apt-get update&
    apt-get install -y squid3 curl nano sysv-rc-conf ulatency ulatencyd&
     
    cd /etc/ssh/
 
    echo "$(sed 's/22/443/g' sshd_config)" > sshd_config
    echo "" >> sshd_config    
    echo "Port 22" >> sshd_config     
     
    ip=$(wget -qO - icanhazip.com)
     
    echo "# PORTAS DE ACESSO NO SQUID" > /etc/squid3/squid.conf
    echo "http_port 80" >> /etc/squid3/squid.conf
    echo "http_port 8080" >> /etc/squid3/squid.conf
    echo "http_port 8799" >> /etc/squid3/squid.conf
    echo "http_port 3128" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# NOME DO SERVIDOR" >> /etc/squid3/squid.conf
    echo "visible_hostname Crazzy" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# ACL DE CONEXAO" >> /etc/squid3/squid.conf
    echo "acl accept src $ip" >> /etc/squid3/squid.conf
    echo "acl ip url_regex -i $ip" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# CACHE DO SQUID" >> /etc/squid3/squid.conf
    echo "cache_mem 200 MB" >> /etc/squid3/squid.conf
    echo "maximum_object_size_in_memory 32 KB" >> /etc/squid3/squid.conf
    echo "maximum_object_size 1024 MB" >> /etc/squid3/squid.conf
    echo "minimum_object_size 0 KB" >> /etc/squid3/squid.conf
    echo "cache_swap_low 90" >> /etc/squid3/squid.conf
    echo "cache_swap_high 95" >> /etc/squid3/squid.conf
    echo "cache_dir ufs /var/spool/squid3 30 16 256" >> /etc/squid3/squid.conf
    echo "access_log /var/log/squid3/access.log squid" >> /etc/squid3/squid.conf
    echo "cache_log /var/log/squid3/cache.log" >> /etc/squid3/squid.conf
    echo "cache_store_log /var/log/squid3/store.log" >> /etc/squid3/squid.conf
    echo "pid_filename /var/log/squid3/squid3.pid" >> /etc/squid3/squid.conf
    echo "mime_table /usr/share/squid3/mime.conf" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# ACESSOS ACL" >> /etc/squid3/squid.conf
    echo "http_access allow accept" >> /etc/squid3/squid.conf
    echo "http_access allow ip" >> /etc/squid3/squid.conf
    echo "http_access deny all" >> /etc/squid3/squid.conf
    echo "cache deny all" >> /etc/squid3/squid.conf
 
    sysv-rc-conf squid3 on
 
    service squid3 restart
 
    service ssh restart
     
    clear
    echo -e "\033[0;36m====================================================\033[0m"
   echo -e "\033[0;31mDesenvolvedor Do Script:\033[0;36m@MatheusR\033[0m"
   echo -e "\033[0;31mSeu Sistema Operacional: $f Ubuntu\033[0m"
   echo -e "\033[0;31mIp Da Sua VPS:\033[0;36m $ip\033[0m"
   echo -e "\033[0;31mSeu Squid Esta Configurado Para Operar Nas Portas:\033[0;36m80, 8080, 3128, 8799\033[0m"
   echo -e "\033[0;31mDropbear Nas Portas:\033[0;36m22 e 443\033[0m"
   echo -e "\033[0;31mVoce Tambem Pode Usa O Ip\033[0;33m127.0.0.1\033[0;31mComo Ip SSH\033[0m"
   echo -e "\033[0;36m=====================================================\033[0m"
   sleep 6
   Crazzy
 
}
 
debian () {
 
clear
echo -e "\033[0;36m======================================\033[0m"
   echo -e "\033[0;32mCONFIGURANDO SEU SQUID...\033[0m"
   sleep 3
   echo -e "\033[0;33m      Sucesso...\033[0m"
   sleep 1 
   echo -e "\033[0;32mCONFIGURANDO SUA VPS...\033[0m"
   sleep 3
   echo -e "\033[0;33m      Sucesso...\033[0m"
   echo -e "\033[0;36m======================================\033[0m"
   sleep 2
     
    apt-get update&
    apt-get install -y squid3 curl nano sysv-rc-conf ulatency ulatencyd&
     
    cd /etc/ssh/
 
    echo "$(sed 's/22/443/g' sshd_config)" > sshd_config
    echo "" >> sshd_config    
    echo "Port 22" >> sshd_config     
     
    ip=$(wget -qO - icanhazip.com)
     
    echo "# PORTAS DE ACESSO NO SQUID" > /etc/squid3/squid.conf
    echo "http_port 80" >> /etc/squid3/squid.conf
    echo "http_port 8080" >> /etc/squid3/squid.conf
    echo "http_port 8799" >> /etc/squid3/squid.conf
    echo "http_port 3128" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# NOME DO SERVIDOR" >> /etc/squid3/squid.conf
    echo "visible_hostname Crazzy" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# ACL DE CONEXAO" >> /etc/squid3/squid.conf
    echo "acl accept src $ip" >> /etc/squid3/squid.conf
    echo "acl ip url_regex -i $ip" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# CACHE DO SQUID" >> /etc/squid3/squid.conf
    echo "cache_mem 200 MB" >> /etc/squid3/squid.conf
    echo "maximum_object_size_in_memory 32 KB" >> /etc/squid3/squid.conf
    echo "maximum_object_size 1024 MB" >> /etc/squid3/squid.conf
    echo "minimum_object_size 0 KB" >> /etc/squid3/squid.conf
    echo "cache_swap_low 90" >> /etc/squid3/squid.conf
    echo "cache_swap_high 95" >> /etc/squid3/squid.conf
    echo "cache_dir ufs /var/spool/squid3 30 16 256" >> /etc/squid3/squid.conf
    echo "access_log /var/log/squid3/access.log squid" >> /etc/squid3/squid.conf
    echo "cache_log /var/log/squid3/cache.log" >> /etc/squid3/squid.conf
    echo "cache_store_log /var/log/squid3/store.log" >> /etc/squid3/squid.conf
    echo "pid_filename /var/log/squid3/squid3.pid" >> /etc/squid3/squid.conf
    echo "mime_table /usr/share/squid3/mime.conf" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "" >> /etc/squid3/squid.conf
    echo "# ACESSOS ACL" >> /etc/squid3/squid.conf
    echo "http_access allow accept" >> /etc/squid3/squid.conf
    echo "http_access allow ip" >> /etc/squid3/squid.conf
    echo "http_access deny all" >> /etc/squid3/squid.conf
    echo "cache deny all" >> /etc/squid3/squid.conf
 
    sysv-rc-conf squid3 on
 
    service squid3 restart
 
    service ssh restart
     
    clear
   echo -e "\033[0;36m====================================================\033[0m"
   echo -e "\033[0;31mDesenvolvedor Do Script:\033[0;36m@MatheusR\033[0m"
   echo -e "\033[0;31mSeu Sistema Operacional: $f Debian\033[0m"
   echo -e "\033[0;31mIp Da Sua VPS:\033[0;36m $ip\033[0m"
   echo -e "\033[0;31mSeu Squid Esta Configurado Para Operar Nas Portas:\033[0;36m80, 8080, 3128, 8799\033[0m"
   echo -e "\033[0;31mDropbear Nas Portas:\033[0;36m22 e 443\033[0m"
   echo -e "\033[0;31mVoce Tambem Pode Usa O Ip\033[0;33m127.0.0.1\033[0;31mComo Ip SSH\033[0m"
   echo -e "\033[0;36m=====================================================\033[0m"
   sleep 6
    Crazzy
}
 
    if cat /etc/issue | grep "Debian" 1>/dev/null 2>/dev/null; then 
     
    debian
     
    elif cat /etc/issue | grep "Ubuntu 16" 1>/dev/null 2>/dev/null; then 
     
    ubuntu16
     
    elif cat /etc/issue | grep "Ubuntu" 1>/dev/null 2>/dev/null; then 
     
    ubuntu
     
    else
    echo -e "Sistema não compatível, Voltando Ao Menu..."
    sleep 4
    Crazzy
fi; ;;
2)
   CriarUsuarios
   sleep 4
   Crazzy; ;;
3)
   DeletarUsuario
   sleep 4
   Crazzy; ;;
4)
   MudarSenha
   sleep 4
   Crazzy; ;;
5)
   AlterarData
   sleep 4
   Crazzy; ;;
6)
   Conectados
   sleep 10
   Crazzy; ;;
7) 
   Banner
   sleep 3
   Crazzy; ;;
8)
   AddHost
   sleep 3
   Crazzy; ;;
9)
   detalhes
   sleep 10
   Crazzy; ;;
10)
   rm -rf /bin/Crazzy > /dev/null 2> /dev/null
   echo -e "$f Script Desinstalado Com Sucesso $x"
   sleep 1; ;;
    
*)
   echo -e "$a Opcao Invalida $x"
   sleep 2
   Crazzy; ;;
 
esac
