#!/bin/bash
x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"
clear
 
   echo -e "$f Qual o Nome Do Usuario Que Deseja Excluir? $x"
   read nome
   userdel --force $nome > /dev/null 2>/dev/null
   echo -e "\033[0;36m O Usuario $nome Foi Excluido \033[0m"
 
