#!/bin/bash

x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"

clear
 
script="$a CrazzyScript $x"
dono="$a MatheusR $x"
versao="$a V1.0 $x"
data="$a 10/04/2017 $x"
 
echo -e "$f Nome Do Script: $script"
echo -e "$f Versão: $versao"
echo -e "$f Desenvolvido Por: $dono"
echo -e "$f Data De Criação: $data"
