#!/bin/sh
 
clear
 
x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"
 
 
echo "\033[1;41;36mOla,  Meu Nome e CrazzyScript, Fui Criado Para Ajudar Voce a Gerenciar Sua Vps, Mas Para Continuarmos, Preciso Saber Se Voce Concorda Que Ao Avançar Com a Instalação Desse Script, O Desenvolvedor Do Mesmo, Nao Se Responsabiliza e Nem Da Suporte A Qualquer Erro Ou Mal Funcionamento De Sua Maquina\033[0m [s/n]:"
read s
 if [ "$s" = "s" ];then
   clear
   else
   exit
 fi
 
echo "\033[1;41;36mEeiii, Antes De Continuar, Quero Falar Que Eu Nao Configuro Sua Vps Logo De Cara, Entao Se Sua Vps e Nova E Voce Nunca Usou Ela No Http Injector Ou Em Outro App De Net Free Ou Ate Mesmo Se Quiser Configurar Novamente e So Escolher A Opcao "1" Do Meu Menu. \033[0m"
echo
echo "$f Aperte Enter Para Continuar $x "
read segue
clear
 
mkdir /etc/Crazzydir 2> /dev/null
mkdir /etc/Crazzydir/senha 2>/dev/null
mkdir /etc/Crazzydir/limite 2> /dev/null
 
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/Limite
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/AddHost
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/AlterarData
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/Banner
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/Conectados
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/CriarUsuarios
wget -O https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/DeletarUsuario


 
wget -O /bin/Crazzy https://dropbox.com/s/zksoebd954gr9gs/Crazzy.sh
chmod a+x /bin/Crazzy
 
clear
 
echo "$f Instalação Concluida Com Sucesso!!! $x"
echo "$f Script Desenvolvido Por $a MatheusR $x"
echo "$f Para Acessar o Menu, Digite $a Crazzy $x"
 
exit
