#!/bin/sh
 
clear
 
x="\033[0m"
a="\033[1;31m"
b="\033[1;32m"
c="\033[1;33m"
d="\033[1;34m"
e="\033[1;35m"
f="\033[1;36m"
g="\033[1;41m"
 
 
echo "\033[1;41;36mOla,  Meu Nome e CrazzyScript, Fui Criado Para Ajudar Voce a Gerenciar Sua Vps, Mas Para Continuarmos, Preciso Saber Se Voce Concorda Que Ao Avançar Com a Instalação Desse Script, O Desenvolvedor Do Mesmo, Nao Se Responsabiliza e Nem Da Suporte A Qualquer Erro Ou Mal Funcionamento De Sua Maquina\033[0m [s/n]:"
read s
 if [ "$s" = "s" ];then
   clear
   else
   exit
 fi
 
echo "\033[1;41;36mEeiii, Antes De Continuar, Quero Falar Que Eu Nao Configuro Sua Vps Logo De Cara, Entao Se Sua Vps e Nova E Voce Nunca Usou Ela No Http Injector Ou Em Outro App De Net Free Ou Ate Mesmo Se Quiser Configurar Novamente e So Escolher A Opcao "1" Do Meu Menu. \033[0m"
echo
echo "$f Aperte Enter Para Continuar $x "
read segue
clear
 
mkdir /etc/Crazzydir 2> /dev/null
mkdir /etc/Crazzydir/senha 2>/dev/null
mkdir /etc/Crazzydir/limite 2> /dev/null

rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -0- 
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/Limite > /bin/Limite
chmod +x /bin/limite

rm -rf /bin/AddHost 2>/dev/nul
wget -o /dev/null -0-
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/AddHost > /bin/AddHost
chmod +x /bin/AddHost

rm -rf /bin/AlterarData 2>/dev/null
wget -o /dev/null -0- 
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/AlterarData > /AlterarData
chmod +x /bin/AlterarData

rm -rf /bin/Banner 2>/dev/null
wget -o /dev/null -0- 
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/Banner > /bin/Banner
chmod +x /bin/Banner

rm -rf /bin/Conectados 2>/dev/null
wget -o /dev/null -0-
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/Conectados > /bin/Conectados
chmod +x /bin/Conectados 

rm -rf /bin/CriarUsuarios 2>/dev/null
wget -o /dev/null -0-
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/CriarUsuuarios > /bin/CriarUsuarios
chmod +x /bin/CriarUsuarios

rm -rf /bin/Crazzy 2>/dev/null
wget -o /dev/null -0-
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/CrazzyMenu > /bin/Crazzy
chmod +x /bin/Crazzy

rm -rf /bin/DeletarUsuario 2>/dev/null
wget -o /dev/null -0-
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/DeletarUsuario > /bin/DeletarUsuario
chmod +x /bin/DeletarUsuario
 
rm -rf /bin/MudarSenha 2>/dev/null
wget  -o /dev/null -0-
https://raw.githubusercontent.com/MatheusRochaXtudo/Crazzy/master/MudarSenha > /bin/MudarSenha
chmod +x /bin/Mudar/Senha
 
clear
 
echo "$f Instalação Concluida Com Sucesso!!! $x"
echo "$f Script Desenvolvido Por $a MatheusR $x"
echo "$f Para Acessar o Menu, Digite $a Crazzy $x"
 
exit
